In [1]:
from shared import student_trends_df, staffing_df

In [3]:
student_trends_df.shape

(104, 18)

In [19]:
student_staffing_df = staffing_df[staffing_df['employee_type'] == 'student']
student_staffing_df = student_staffing_df[student_staffing_df['date'] == student_staffing_df['date'].max()]
print(student_staffing_df.shape)

student_staffing_df.to_csv('student_staffing_df.csv', index=False)
student_staffing_df

(43, 15)

             ID            full_name  ...  cdl cdl_training_start_date
2382  500666641   Matthew Swearingen  ...  1.0              2026-06-09
2383  500635005      Yuan Shuo Chang  ...  0.0              2025-08-18
2384  500646501         Zachary Buhr  ...  1.0              2025-02-14
2385  500715582            Yunong Wu  ...  0.0                     NaN
2386  500657467           Adil Zafar  ...  0.0                     NaN
2387  500678557           Yujie Yang  ...  0.0                     NaN
2388  500734219            Ean Bowie  ...  0.0                     NaN
2389  500788162            Kainan Li  ...  0.0              2024-03-14
2390  500765311       Olivia McGrath  ...  1.0              2024-08-20
2391  500663430        Julien Lovitz  ...  1.0              2024-10-28
2392  500820909        Oliver Shores  ...  0.0              2026-06-29
2393  500793864           Jason Barr  ...  1.0              2026-03-24
2394  500835525          Zongyang Li  ...  1.0              2025-06-23
2395  500789126        Nickyah Vales  ...  1.0              2024-09-26
2396  500829854      Gianna Marchese  ...  1.0              2026-06-06
2397  500727924         Wesley Holtz  ...  1.0              2025-04-08
2398  500885710         Noah Pierron  ...  0.0                     NaN
2399  500878544     Zhenis Kenzhekey  ...  1.0              2024-11-22
2400  500857431           Cheng Peng  ...  0.0                     NaN
2401  500894043          Duniyo Jama  ...  0.0                     NaN
2402  500929307         Yuxuan Jiang  ...  0.0                     NaN
2403  500793664     Rachel Robertson  ...  1.0              2025-05-14
2404  500753387      Ronald Frempong  ...  1.0              2025-07-08
2405  500953917           Dion Watts  ...  0.0              2026-05-25
2406  500895759           Chris Baik  ...  1.0              2025-09-04
2407  500979000  Florin Socol-Boeriu  ...  1.0              2026-03-26
2408  500978586     Christian Geiman  ...  1.0              2026-01-14
2409  500896272         Aarush Katta  ...  0.0                     NaN
2410  500471133     Ibrahim Alhassan  ...  1.0              2025-12-23
2411  500953990         John DeHaven  ...  1.0              2025-12-28
2412  109007170   Glauco Fontgalland  ...  0.0                     NaN
2413  500897180     Nathaniel Miller  ...  0.0                     NaN
2414  500625849       Samuel McQuate  ...  0.0                     NaN
2415  500845517    Mohamed Abdisalam  ...  0.0                     NaN
2416  501018154           Anna Irwin  ...  0.0                     NaN
2417  500872833       Jackson O'Hara  ...  0.0                     NaN
2418  501075234         Wilson Grubb  ...  0.0                     NaN
2419  501081065          Mikai Thiam  ...  0.0              2026-04-09
2420  500995504       Rodrigo Flores  ...  0.0                     NaN
2421  500726388       Justin Higgins  ...  0.0                     NaN
2422  500977292        Darrell Zhang  ...  0.0                     NaN
2423  500960479     Emmanuel Verzola  ...  0.0                     NaN
2424  501011605          Laura Adair  ...  0.0              2026-07-07

[43 rows x 15 columns]

In [18]:
student_trends_df = student_trends_df[student_trends_df['date'] == student_trends_df['date'].max()]
student_trends_df = student_trends_df[student_trends_df['active'] == 1]
print(student_trends_df.shape)

student_trends_df.to_csv('student_trends_df.csv', index=False)
student_trends_df

(45, 18)

                  full_name  ...  cdl_status
2                Adil Zafar  ...         NaN
6               Laura Adair  ...         NaN
16            Manny Verzola  ...         NaN
33            Darrell Zhang  ...         NaN
36           Justin Higgins  ...         NaN
43           Rodrigo Flores  ...         NaN
45              Mikai Thiam  ...         NaN
50           Jackson O'Hara  ...         NaN
51      Florin Socol-Boeriu  ...         NaN
52             Noah Pierron  ...         NaN
54       Glauco Fontgalland  ...         NaN
55       Matthew Swearingen  ...         NaN
57               Anna Irwin  ...         NaN
58        Mohamed Abdisalam  ...         NaN
59              Sam McQuate  ...         NaN
60              Nate Miller  ...         NaN
61         Ibrahim Alhassan  ...         NaN
62             John DeHaven  ...         NaN
63         Christian Geiman  ...         NaN
64               Jason Barr  ...         NaN
65             Aarush Katta  ...         NaN
66            Oliver Shores  ...         NaN
68     Yuxuan "Jason" Jiang  ...         NaN
71      Cheng "George" Peng  ...         NaN
72               Yujie Yang  ...         NaN
73               Dion Watts  ...         NaN
74               Chris Baik  ...         NaN
75          Gianna Marchese  ...         NaN
77          Ronald Frempong  ...         NaN
78                Ean Bowie  ...         NaN
79                  Noah Li  ...         NaN
80  Yuan Shuo "James" Chang  ...         NaN
81             Wesley Holtz  ...         NaN
83             Zachary Buhr  ...         NaN
84         Rachel Robertson  ...         NaN
85              Duniyo Jama  ...         NaN
86           Vivek Majumdar  ...         NaN
87         Zhenis Kenzhekey  ...         NaN
89               Jei Lovitz  ...         NaN
90            Nickyah Vales  ...         NaN
91           Olivia McGrath  ...         NaN
92       Kainan "Kelvin" Li  ...         NaN
93          Niyanna Wallace  ...         NaN
94              Louise Hogg  ...         NaN
95             Ty McKitrick  ...         NaN

[45 rows x 18 columns]

In [4]:
import pandas as pd
path = 'C:/Users/morgan.1461/OneDrive - The Ohio State University/Training & Staffing Master.xlsx.url'

df = pd.read_excel(path, sheet_name='Students')

ValueError: Excel file format cannot be determined, you must specify an engine manually.